import { ThemeConfig } from '../types';

export const THEMES: ThemeConfig[] = [
  {
    id: 'classic-dark',
    name: 'Classic Dark',
    mode: 'dark',
    accent: '#ec4899',
    bgPreview: '#09090b',
    borderPreview: 'rgba(255,255,255,0.1)',
    description: 'Deep obsidian #09090b with sleek glass layers and neon pink accent.',
  },
  {
    id: 'classic-light',
    name: 'Classic Light',
    mode: 'light',
    accent: '#ec4899',
    bgPreview: '#fafafa',
    borderPreview: '#e4e4e7',
    description: 'Crisp monochrome with soft pink selection and airy surfaces.',
  },
  {
    id: 'starry-skies',
    name: 'Starry Skies',
    mode: 'dark',
    accent: '#7ba0d4',
    bgPreview: '#0a0e27',
    borderPreview: 'rgba(100,120,200,0.2)',
    description: 'Midnight cosmic navy with celestial sapphire highlights.',
  },
  {
    id: 'spring-blossom',
    name: 'Spring Blossom',
    mode: 'light',
    accent: '#e891b0',
    bgPreview: '#fdf6f8',
    borderPreview: '#f0d4dc',
    description: 'Warm sakura pinks, floral cream background and soft petal glow.',
  },
  {
    id: 'summer-splash',
    name: 'Summer Splash',
    mode: 'light',
    accent: '#2196f3',
    bgPreview: '#f0f7ff',
    borderPreview: '#c4daf0',
    description: 'Vibrant ocean cyan, refreshing azure skies and sunlight.',
  },
  {
    id: 'falling-leaves',
    name: 'Falling Leaves',
    mode: 'light',
    accent: '#d2691e',
    bgPreview: '#faf5f0',
    borderPreview: '#e4d4c0',
    description: 'Autumn amber, warm ochre, rustic crimson and earthy serenity.',
  },
  {
    id: 'frosty-flakes',
    name: 'Frosty Flakes',
    mode: 'light',
    accent: '#4a90d9',
    bgPreview: '#f0f5fa',
    borderPreview: '#c8d8e8',
    description: 'Crisp ice-blue, arctic silver sheen and frosted glass textures.',
  },
  {
    id: 'holy-ramadan',
    name: 'Holy Ramadan',
    mode: 'dark',
    accent: '#c9a84c',
    bgPreview: '#0d1f1c',
    borderPreview: 'rgba(200,168,80,0.2)',
    description: 'Majestic deep emerald and radiant crescent gold illumination.',
  },
  {
    id: 'cozy-christmas',
    name: 'Cozy Christmas',
    mode: 'dark',
    accent: '#e74c3c',
    bgPreview: '#142417',
    borderPreview: 'rgba(200,50,50,0.2)',
    description: 'Evergreen forest pines, festive garnet red and holiday warmth.',
  },
  {
    id: 'canada-day',
    name: 'Canada Day',
    mode: 'light',
    accent: '#d52b1e',
    bgPreview: '#fafafa',
    borderPreview: '#fecaca',
    description: 'Vivid maple red, clean snow white and bold Canadian spirit.',
  },
];
